swag:
	swag init -g cmd/main.go --parseDependency --parseInternal
	cp ./docs/swagger.json ./docs/beer-api-openapi.json
	cp ./docs/swagger.yaml ./docs/beer-api-openapi.yaml

	@if [ -f "./docs/docs.go" ]; then \
		fl="$$(head -n1 ./docs/docs.go | tr -d '\r\n')"; \
		if printf "%s" "$$fl" | grep -q "swaggo/swag"; then \
			{ printf "// Code generated by swaggo/swag; DO NOT EDIT.\n\n"; tail -n +2 ./docs/docs.go; } > ./docs/docs.go.tmp && mv ./docs/docs.go.tmp ./docs/docs.go; \
		fi; \
	fi

	@if [ -f "./docs/docs.go" ]; then \
		lc="$$(tail -c1 ./docs/docs.go | od -An -t x1 | tr -d ' ')"; \
		if [ "$$lc" != "0a" ]; then \
			printf "\n" >> ./docs/docs.go; \
		fi; \
	fi

install-swag:
	go install -v github.com/swaggo/swag/cmd/swag@latest

mockery-install:
	go install -v github.com/vektra/mockery/v3@v3.2.5

install-lint-windows-chocolatey:
	choco install golangci-lint

mockery:
	mockery --config .mockery.yml

# Define aquí todos los patrones de ruta que quieres probar

PKG_PATHS := ./beer/...

# 1) Listamos todos los paquetes de esas fuentes

# 2) Filtramos los que NO contienen “/mocks/”

# 3) Ejecutamos las pruebas con cobertura

# 4) Mostramos el informe

go-test:
	@ALL_PKGS=$$(go list $(PKG_PATHS)) && \
	PKGS=$$(echo "$$ALL_PKGS" | tr ' ' '\n' | grep -v '/mocks/') && \
	go test -coverprofile=coverage.out -v $$PKGS && \
	go tool cover -func=coverage.out
	
# Genera un informe de cobertura de tests en formato HTML.

go-test-report:
	go tool cover -html=coverage.out