swag:
	swag init -g cmd/main.go --parseDependency --parseInternal
	cp ./docs/swagger.json ./docs/beer-api-openapi.json
	cp ./docs/swagger.yaml ./docs/beer-api-openapi.yaml

	@if [ -f "./docs/docs.go" ]; then \
		fl="$$(head -n1 ./docs/docs.go | tr -d '\r\n')"; \
		if printf "%s" "$$fl" | grep -q "swaggo/swag"; then \
			{ printf "// Code generated by swaggo/swag; DO NOT EDIT.\n\n"; tail -n +2 ./docs/docs.go; } > ./docs/docs.go.tmp && mv ./docs/docs.go.tmp ./docs/docs.go; \
		fi; \
	fi

	@if [ -f "./docs/docs.go" ]; then \
		lc="$$(tail -c1 ./docs/docs.go | od -An -t x1 | tr -d ' ')"; \
		if [ "$$lc" != "0a" ]; then \
			printf "\n" >> ./docs/docs.go; \
		fi; \
	fi

install-swag:
	go install -v github.com/swaggo/swag/cmd/swag@latest

mockery-install:
	go install -v github.com/vektra/mockery/v3@v3.2.5

install-lint-windows-chocolatey:
	choco install golangci-lint

mockery:
	mockery --config .mockery.yml