// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"context"
	"go_trainning/beer-api/beer/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBeerService creates a new instance of MockBeerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerService {
	mock := &MockBeerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBeerService is an autogenerated mock type for the BeerService type
type MockBeerService struct {
	mock.Mock
}

type MockBeerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeerService) EXPECT() *MockBeerService_Expecter {
	return &MockBeerService_Expecter{mock: &_m.Mock}
}

// CreateBeerWithId provides a mock function for the type MockBeerService
func (_mock *MockBeerService) CreateBeerWithId(ctx context.Context, beers *model.BeersRequest) error {
	ret := _mock.Called(ctx, beers)

	if len(ret) == 0 {
		panic("no return value specified for CreateBeerWithId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.BeersRequest) error); ok {
		r0 = returnFunc(ctx, beers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBeerService_CreateBeerWithId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBeerWithId'
type MockBeerService_CreateBeerWithId_Call struct {
	*mock.Call
}

// CreateBeerWithId is a helper method to define mock.On call
//   - ctx context.Context
//   - beers *model.BeersRequest
func (_e *MockBeerService_Expecter) CreateBeerWithId(ctx interface{}, beers interface{}) *MockBeerService_CreateBeerWithId_Call {
	return &MockBeerService_CreateBeerWithId_Call{Call: _e.mock.On("CreateBeerWithId", ctx, beers)}
}

func (_c *MockBeerService_CreateBeerWithId_Call) Run(run func(ctx context.Context, beers *model.BeersRequest)) *MockBeerService_CreateBeerWithId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.BeersRequest
		if args[1] != nil {
			arg1 = args[1].(*model.BeersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBeerService_CreateBeerWithId_Call) Return(err error) *MockBeerService_CreateBeerWithId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBeerService_CreateBeerWithId_Call) RunAndReturn(run func(ctx context.Context, beers *model.BeersRequest) error) *MockBeerService_CreateBeerWithId_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBeers provides a mock function for the type MockBeerService
func (_mock *MockBeerService) GetAllBeers(ctx context.Context) ([]model.Beers, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeers")
	}

	var r0 []model.Beers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Beers, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Beers); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerService_GetAllBeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBeers'
type MockBeerService_GetAllBeers_Call struct {
	*mock.Call
}

// GetAllBeers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBeerService_Expecter) GetAllBeers(ctx interface{}) *MockBeerService_GetAllBeers_Call {
	return &MockBeerService_GetAllBeers_Call{Call: _e.mock.On("GetAllBeers", ctx)}
}

func (_c *MockBeerService_GetAllBeers_Call) Run(run func(ctx context.Context)) *MockBeerService_GetAllBeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBeerService_GetAllBeers_Call) Return(beerss []model.Beers, err error) *MockBeerService_GetAllBeers_Call {
	_c.Call.Return(beerss, err)
	return _c
}

func (_c *MockBeerService_GetAllBeers_Call) RunAndReturn(run func(ctx context.Context) ([]model.Beers, error)) *MockBeerService_GetAllBeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetBeerById provides a mock function for the type MockBeerService
func (_mock *MockBeerService) GetBeerById(ctx context.Context, id uint) (model.Beers, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBeerById")
	}

	var r0 model.Beers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (model.Beers, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) model.Beers); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Beers)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerService_GetBeerById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBeerById'
type MockBeerService_GetBeerById_Call struct {
	*mock.Call
}

// GetBeerById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBeerService_Expecter) GetBeerById(ctx interface{}, id interface{}) *MockBeerService_GetBeerById_Call {
	return &MockBeerService_GetBeerById_Call{Call: _e.mock.On("GetBeerById", ctx, id)}
}

func (_c *MockBeerService_GetBeerById_Call) Run(run func(ctx context.Context, id uint)) *MockBeerService_GetBeerById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBeerService_GetBeerById_Call) Return(beers model.Beers, err error) *MockBeerService_GetBeerById_Call {
	_c.Call.Return(beers, err)
	return _c
}

func (_c *MockBeerService_GetBeerById_Call) RunAndReturn(run func(ctx context.Context, id uint) (model.Beers, error)) *MockBeerService_GetBeerById_Call {
	_c.Call.Return(run)
	return _c
}

// GetOneBoxPrice provides a mock function for the type MockBeerService
func (_mock *MockBeerService) GetOneBoxPrice(ctx context.Context, id uint, currencyPay string, quantity int) (model.PriceResponse, error) {
	ret := _mock.Called(ctx, id, currencyPay, quantity)

	if len(ret) == 0 {
		panic("no return value specified for GetOneBoxPrice")
	}

	var r0 model.PriceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, int) (model.PriceResponse, error)); ok {
		return returnFunc(ctx, id, currencyPay, quantity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, int) model.PriceResponse); ok {
		r0 = returnFunc(ctx, id, currencyPay, quantity)
	} else {
		r0 = ret.Get(0).(model.PriceResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, int) error); ok {
		r1 = returnFunc(ctx, id, currencyPay, quantity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerService_GetOneBoxPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneBoxPrice'
type MockBeerService_GetOneBoxPrice_Call struct {
	*mock.Call
}

// GetOneBoxPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - currencyPay string
//   - quantity int
func (_e *MockBeerService_Expecter) GetOneBoxPrice(ctx interface{}, id interface{}, currencyPay interface{}, quantity interface{}) *MockBeerService_GetOneBoxPrice_Call {
	return &MockBeerService_GetOneBoxPrice_Call{Call: _e.mock.On("GetOneBoxPrice", ctx, id, currencyPay, quantity)}
}

func (_c *MockBeerService_GetOneBoxPrice_Call) Run(run func(ctx context.Context, id uint, currencyPay string, quantity int)) *MockBeerService_GetOneBoxPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBeerService_GetOneBoxPrice_Call) Return(priceResponse model.PriceResponse, err error) *MockBeerService_GetOneBoxPrice_Call {
	_c.Call.Return(priceResponse, err)
	return _c
}

func (_c *MockBeerService_GetOneBoxPrice_Call) RunAndReturn(run func(ctx context.Context, id uint, currencyPay string, quantity int) (model.PriceResponse, error)) *MockBeerService_GetOneBoxPrice_Call {
	_c.Call.Return(run)
	return _c
}
