// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"context"
	"go_trainning/beer-api/beer/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBeerRepository creates a new instance of MockBeerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerRepository {
	mock := &MockBeerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBeerRepository is an autogenerated mock type for the BeerRepository type
type MockBeerRepository struct {
	mock.Mock
}

type MockBeerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeerRepository) EXPECT() *MockBeerRepository_Expecter {
	return &MockBeerRepository_Expecter{mock: &_m.Mock}
}

// CreateBeerWithId provides a mock function for the type MockBeerRepository
func (_mock *MockBeerRepository) CreateBeerWithId(ctx context.Context, beers *model.Beers) error {
	ret := _mock.Called(ctx, beers)

	if len(ret) == 0 {
		panic("no return value specified for CreateBeerWithId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Beers) error); ok {
		r0 = returnFunc(ctx, beers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBeerRepository_CreateBeerWithId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBeerWithId'
type MockBeerRepository_CreateBeerWithId_Call struct {
	*mock.Call
}

// CreateBeerWithId is a helper method to define mock.On call
//   - ctx context.Context
//   - beers *model.Beers
func (_e *MockBeerRepository_Expecter) CreateBeerWithId(ctx interface{}, beers interface{}) *MockBeerRepository_CreateBeerWithId_Call {
	return &MockBeerRepository_CreateBeerWithId_Call{Call: _e.mock.On("CreateBeerWithId", ctx, beers)}
}

func (_c *MockBeerRepository_CreateBeerWithId_Call) Run(run func(ctx context.Context, beers *model.Beers)) *MockBeerRepository_CreateBeerWithId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Beers
		if args[1] != nil {
			arg1 = args[1].(*model.Beers)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBeerRepository_CreateBeerWithId_Call) Return(err error) *MockBeerRepository_CreateBeerWithId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBeerRepository_CreateBeerWithId_Call) RunAndReturn(run func(ctx context.Context, beers *model.Beers) error) *MockBeerRepository_CreateBeerWithId_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBeers provides a mock function for the type MockBeerRepository
func (_mock *MockBeerRepository) GetAllBeers(ctx context.Context) ([]model.Beers, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeers")
	}

	var r0 []model.Beers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Beers, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Beers); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerRepository_GetAllBeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBeers'
type MockBeerRepository_GetAllBeers_Call struct {
	*mock.Call
}

// GetAllBeers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBeerRepository_Expecter) GetAllBeers(ctx interface{}) *MockBeerRepository_GetAllBeers_Call {
	return &MockBeerRepository_GetAllBeers_Call{Call: _e.mock.On("GetAllBeers", ctx)}
}

func (_c *MockBeerRepository_GetAllBeers_Call) Run(run func(ctx context.Context)) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBeerRepository_GetAllBeers_Call) Return(beerss []model.Beers, err error) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Return(beerss, err)
	return _c
}

func (_c *MockBeerRepository_GetAllBeers_Call) RunAndReturn(run func(ctx context.Context) ([]model.Beers, error)) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetBeerById provides a mock function for the type MockBeerRepository
func (_mock *MockBeerRepository) GetBeerById(ctx context.Context, id uint) (model.Beers, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBeerById")
	}

	var r0 model.Beers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (model.Beers, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) model.Beers); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Beers)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerRepository_GetBeerById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBeerById'
type MockBeerRepository_GetBeerById_Call struct {
	*mock.Call
}

// GetBeerById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBeerRepository_Expecter) GetBeerById(ctx interface{}, id interface{}) *MockBeerRepository_GetBeerById_Call {
	return &MockBeerRepository_GetBeerById_Call{Call: _e.mock.On("GetBeerById", ctx, id)}
}

func (_c *MockBeerRepository_GetBeerById_Call) Run(run func(ctx context.Context, id uint)) *MockBeerRepository_GetBeerById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBeerRepository_GetBeerById_Call) Return(beers model.Beers, err error) *MockBeerRepository_GetBeerById_Call {
	_c.Call.Return(beers, err)
	return _c
}

func (_c *MockBeerRepository_GetBeerById_Call) RunAndReturn(run func(ctx context.Context, id uint) (model.Beers, error)) *MockBeerRepository_GetBeerById_Call {
	_c.Call.Return(run)
	return _c
}
