// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"go_trainning/beer-api/beer/external/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCurrencyLayer creates a new instance of MockCurrencyLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrencyLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrencyLayer {
	mock := &MockCurrencyLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCurrencyLayer is an autogenerated mock type for the CurrencyLayer type
type MockCurrencyLayer struct {
	mock.Mock
}

type MockCurrencyLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurrencyLayer) EXPECT() *MockCurrencyLayer_Expecter {
	return &MockCurrencyLayer_Expecter{mock: &_m.Mock}
}

// GetExchangeCurrency provides a mock function for the type MockCurrencyLayer
func (_mock *MockCurrencyLayer) GetExchangeCurrency(currency string, currencyBeer string, amountBeer float64) (model.CurrencyConversionResponse, error) {
	ret := _mock.Called(currency, currencyBeer, amountBeer)

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeCurrency")
	}

	var r0 model.CurrencyConversionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, float64) (model.CurrencyConversionResponse, error)); ok {
		return returnFunc(currency, currencyBeer, amountBeer)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, float64) model.CurrencyConversionResponse); ok {
		r0 = returnFunc(currency, currencyBeer, amountBeer)
	} else {
		r0 = ret.Get(0).(model.CurrencyConversionResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, float64) error); ok {
		r1 = returnFunc(currency, currencyBeer, amountBeer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCurrencyLayer_GetExchangeCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchangeCurrency'
type MockCurrencyLayer_GetExchangeCurrency_Call struct {
	*mock.Call
}

// GetExchangeCurrency is a helper method to define mock.On call
//   - currency string
//   - currencyBeer string
//   - amountBeer float64
func (_e *MockCurrencyLayer_Expecter) GetExchangeCurrency(currency interface{}, currencyBeer interface{}, amountBeer interface{}) *MockCurrencyLayer_GetExchangeCurrency_Call {
	return &MockCurrencyLayer_GetExchangeCurrency_Call{Call: _e.mock.On("GetExchangeCurrency", currency, currencyBeer, amountBeer)}
}

func (_c *MockCurrencyLayer_GetExchangeCurrency_Call) Run(run func(currency string, currencyBeer string, amountBeer float64)) *MockCurrencyLayer_GetExchangeCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCurrencyLayer_GetExchangeCurrency_Call) Return(currencyConversionResponse model.CurrencyConversionResponse, err error) *MockCurrencyLayer_GetExchangeCurrency_Call {
	_c.Call.Return(currencyConversionResponse, err)
	return _c
}

func (_c *MockCurrencyLayer_GetExchangeCurrency_Call) RunAndReturn(run func(currency string, currencyBeer string, amountBeer float64) (model.CurrencyConversionResponse, error)) *MockCurrencyLayer_GetExchangeCurrency_Call {
	_c.Call.Return(run)
	return _c
}
