// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "go_trainning/beer-api/beer/model"
)

// BeerRepository is an autogenerated mock type for the BeerRepository type
type BeerRepository struct {
	mock.Mock
}

// CreateBeerWithId provides a mock function with given fields: ctx, beers
func (_m *BeerRepository) CreateBeerWithId(ctx context.Context, beers *model.Beers) error {
	ret := _m.Called(ctx, beers)

	if len(ret) == 0 {
		panic("no return value specified for CreateBeerWithId")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Beers) error); ok {
		r0 = rf(ctx, beers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllBeers provides a mock function with given fields: ctx
func (_m *BeerRepository) GetAllBeers(ctx context.Context) ([]model.Beers, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeers")
	}

	var r0 []model.Beers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Beers, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Beers); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beers)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBeerById provides a mock function with given fields: ctx, id
func (_m *BeerRepository) GetBeerById(ctx context.Context, id uint) (model.Beers, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBeerById")
	}

	var r0 model.Beers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (model.Beers, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) model.Beers); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.Beers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBeerRepository creates a new instance of BeerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBeerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BeerRepository {
	mock := &BeerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
