// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "go_trainning/beer-api/beer/external/model"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyLayer is an autogenerated mock type for the CurrencyLayer type
type CurrencyLayer struct {
	mock.Mock
}

// GetExchangeCurrency provides a mock function with given fields: currency, currencyBeer, amountBeer
func (_m *CurrencyLayer) GetExchangeCurrency(currency string, currencyBeer string, amountBeer float64) (model.CurrencyConversionResponse, error) {
	ret := _m.Called(currency, currencyBeer, amountBeer)

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeCurrency")
	}

	var r0 model.CurrencyConversionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, float64) (model.CurrencyConversionResponse, error)); ok {
		return rf(currency, currencyBeer, amountBeer)
	}
	if rf, ok := ret.Get(0).(func(string, string, float64) model.CurrencyConversionResponse); ok {
		r0 = rf(currency, currencyBeer, amountBeer)
	} else {
		r0 = ret.Get(0).(model.CurrencyConversionResponse)
	}

	if rf, ok := ret.Get(1).(func(string, string, float64) error); ok {
		r1 = rf(currency, currencyBeer, amountBeer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCurrencyLayer creates a new instance of CurrencyLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyLayer {
	mock := &CurrencyLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
